// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  projectSidebar: [
    'intro',
    {
      type: 'category',
      
      label: 'Documentation tooling',
      items: [
        'documentation-tooling/intro',
        {
          type: 'category',
          label: "Supabase",
          items: ['documentation-tooling/faker/getting-started',
            {
              type: 'category',
              label: "API Reference",
              items: ['documentation-tooling/faker/reference/api-overview', 'documentation-tooling/faker/reference/get-user', 'documentation-tooling/faker/reference/create-user'],
              link: { type: 'doc', id: 'documentation-tooling/faker/reference/api-overview' }
            },
          ],
          link: { type: 'doc', id: 'documentation-tooling/faker/getting-started' }
        }
      ],
      link: { type: 'doc', id: 'documentation-tooling/intro' },
    },
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        'api-documentation/intro',],
      link: { type: 'doc', id: 'api-documentation/intro' },
    },
    {
      type: 'category',
      label: 'Documentation automation',
      items: [
        'docs-automation/intro',],
      link: { type: 'doc', id: 'docs-automation/intro' },
    },
    {
      type: 'category',
      label: 'AI Documentation',
      items: [
        'ai-documentation/intro',],
      link: { type: 'doc', id: 'ai-documentation/intro' },
    },
    {
      type: 'category',
      label: 'Devops & Cloud',
      items: [
        'devops-cloud/intro',],
      link: { type: 'doc', id: 'devops-cloud/intro' },
    },
    {
      type: 'category',
      label: 'Web 3',
      items: [
        'web3-docs/intro',],
      link: { type: 'doc', id: 'web3-docs/intro' },
    },
  ],

};

export default sidebars;
