// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  projectSidebar: [
    'intro',
    {
      type: 'category',

      label: 'Documentation tooling',
      items: [
        {
          type: 'category',
          label: "Supabase",
          items: ['documentation-tooling/supabase/intro', 'documentation-tooling/supabase/getting-started',
            {
              type: 'category',
              label: "Supabase API Reference",
              items: ['documentation-tooling/supabase/reference/create-project', 'documentation-tooling/supabase/reference/delete-project'],
              link: { type: 'doc', id: 'documentation-tooling/supabase/intro' }
            },
          ],
          link: { type: 'doc', id: 'documentation-tooling/supabase/intro' }
        }
      ],
      link: { type: 'doc', id: 'documentation-tooling/supabase/getting-started' },
    },
    {
      type: 'category',
      label: 'API Documentation',
      items:[
        {
          type: 'category',
          label:'Chimoney',
          items: ['api-documentation/getting-started',
            {
              type: 'category',
          label: "Chimoney API Reference",
          items: ['api-documentation/reference/chimoney-api','api-documentation/reference/create-multicurrency-wallet', 'api-documentation/reference/transfer-funds-from-multicurrency-wallets-to-other-wallets-an-email-or-phone-number'],
          link: { type: 'doc', id: 'api-documentation/reference/chimoney-api' }
            }
          ],
      link: { type: 'doc', id: 'api-documentation/getting-started' },

        }
      ]
      
    },
    {
      type: 'category',
      label: 'Documentation Automation',
      items: [
        'docs-automation/sample',],
      link: { type: 'doc', id: 'docs-automation/sample' },
    },
    {
      type: 'category',
      label: 'AI Documentation',
      items: [
        'ai-documentation/reflection',
        'ai-documentation/model_card',
        'ai-documentation/final_doc',
        'ai-documentation/ai_output',
        'ai-documentation/prompt_used',

      ],
      link: { type: 'doc', id: 'ai-documentation/reflection' },
    },
    {
      type: 'category',
      label: 'Devops & Cloud',
      items: [
        'devops-cloud-documentation/overview',
        'devops-cloud-documentation/step_by_step'
      ],
      link: { type: 'doc', id: 'devops-cloud-documentation/overview' },
    },
    // {
    //   type: 'category',
    //   label: 'Web 3',
    //   items: [
    //     'web3-docs/intro',],
    //   link: { type: 'doc', id: 'web3-docs/intro' },
    // },
  ],

};

export default sidebars;
